apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transcode

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres-statefulset.yaml
- redis-statefulset.yaml
- rabbitmq-statefulset.yaml
- api-deployment.yaml
- worker-deployment.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml
- backup-cronjob.yaml

commonLabels:
  app.kubernetes.io/name: transcode
  app.kubernetes.io/managed-by: kustomize
